albumapp/config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  
  resources :albums do
    resources :images
  end
  devise_for :users

  root to: "home#index"

end

albumapp/app/models/album.rb
class Album < ActiveRecord::Base
	
	belongs_to :user
	has_many :images
	# has_one :user
	mount_uploader :thumbnail,ImageUploader
end

albumapp/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :album
	mount_uploader :image, ImageUploader
end

albumapp/app/models/user.rb
class User < ActiveRecord::Base
	  
	# before_action :authenticate_user!
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	       :recoverable, :rememberable, :trackable, :validatable
	
	has_many :albums
	has_many :images, through: :albums


	# validates_format_of :name, :with => /[A-Za-z]+/, :on => :create
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
	validates_length_of :password, :minimum => 5, :on => :create

end

albumapp/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = current_user.albums
    # @albums = Album.all
    # binding.pry
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)
    @album.user = current_user

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :description, :thumbnail)
    end
end

albumapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter :store_location

	def store_location
	  # store last url - this is needed for post-login redirect to whatever the user last visited.
	  return unless request.get? 
	  if (request.path != "/users/sign_in" &&
	      request.path != "/users/sign_up" &&
	      request.path != "/users/password/new" &&
	      request.path != "/users/password/edit" &&
	      request.path != "/users/confirmation" &&
	      request.path != "/users/sign_out" &&
	      !request.xhr?) # don't store ajax calls
	    session[:previous_url] = request.fullpath 
	  end
	end

	def after_sign_in_path_for(resource)
	  	albums_path(current_user)
	end
end

albumapp/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	
  end
end

albumapp/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_filter :set_album

  # GET /images
  # GET /images.json
  def index
    @images = current_user.images
    @album = Album.find(params[:album_id])

  end

  # GET /images/1
  # GET /images/1.json
  def show
    @album = Album.find(params[:album_id])
  end

  # GET /images/new
  def new
    @image = Image.new
    @album = Album.find(params[:album_id])
  end

  # GET /images/1/edit
  def edit
    @album = Album.find(params[:album_id])
  end

  # POST /images
  # POST /images.json
  def create
    @album = Album.find(params[:album_id])
    @image = Image.new(image_params)
    @image.album = @album
    respond_to do |format|
      if @image.save
        # binding.pry
        format.html { redirect_to album_image_path(@album,@image), notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    @album = Album.find(params[:album_id])
    respond_to do |format|
      # binding.pry
      if @image.update(image_params)
        format.html { redirect_to album_image_path(@album,@image), notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @album = Album.find(params[:album_id])
    @image.destroy
    respond_to do |format|
      format.html { redirect_to album_images_path(@album), notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find params[:album_id]
    end
    
    def set_image
    # binding.pry
      @image = Image.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :image, :remove_image)
    end
    # 
end

albumapp/app/helpers/application_helper.rb
module ApplicationHelper
	
end

albumapp/app/helpers/home_helper.rb
module HomeHelper
	
end

albumapp/app/helpers/images_helper.rb
module ImagesHelper
end

albumapp/app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <form class="form-horizontal">
    <% if @album.errors.any? %>
      <div class="form-group" id="error_explanation">
        <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>
        <ul>
        <% @album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <br>
    <div class="panel-body">
    <div class="form-group">
      <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-6 col-md-offset-4">
        <!-- <label for="thumbnail" >Thumbnail:</label> -->
        <div class="carrier-wave-field"><%= f.file_field :thumbnail , title: "Thumbnail" , class: "form-control input-sm" %><br></div>

        <%= f.text_field :title , class: "form-control input-sm" , placeholder: "Title" %><br>

        <%= f.text_area :description , class: "form-control input-sm" , placeholder: "Description"%><br>

        <div class="actions">
          <div class="col-sm-offset-1">
            <%= submit_tag "Create Album", :class => "login-btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
  </form>
<% end %>
<style>
  .carrier-wave-field input {
    color: white;  /*or whatever you want to change*/
}
</style>

albumapp/app/views/albums/edit.html.erb
<div class="container">
  <div class="row">
    <div class="well">
    	<div class="text-right">
      	<%= link_to 'Show', @album %> |
  		  <%= link_to 'Back', albums_path %>
		  </div>
		  <h1 class="text-center">Album Application</h1><br>
    	<div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Editing Album</strong></h1>
            </div>
            <div class="panel-body text-center">
              <%= render 'form' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

albumapp/app/views/albums/index.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="text-right">
        <%= link_to 'New Album', new_album_path %> |
        <%= link_to 'Sign Out', destroy_user_session_path,method: :delete %> |
        <%= link_to 'Edit User Information' , edit_user_registration_path %>
      </div>
      <h1 class="text-center">Album Application</h1>
      <div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Albums</strong></h1>
            </div>
            <div class="panel-body text-center">
              <form role="form">
                <p id="notice"><%= notice %></p>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Thumbnail</th>
                      <th>Title</th>
                      <th>Description</th>
                      <th colspan="6"></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @albums.each do |album| %>
                      <tr>
                        <td><%= image_tag album.thumbnail_url(:thumb) %></td>
                        <td><%= album.title %></td>
                        <td><%= album.description %></td>      
                        <td><%= link_to 'View', album_path(album) %></td>
                        <td><%= link_to 'Update', edit_album_path(album) %></td>
                        <td><%= link_to 'Delete', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <br>

                
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style>
  #container1 {
    background-color: #e2dada;
  }

  .centered-form {
    margin-top: 50px;
    margin-bottom: 50px;
  }

  .centered-form .panel {
    background: rgba(255, 255, 255, 0.8);
    box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
  }

  .table th {
   text-align: center;   
  }
</style>

albumapp/app/views/albums/new.html.erb
<div class="container">
	<div class="row">
  		<div class="well">
			<div class="text-right">
		  		<%= link_to 'Back', albums_path %><br>
			</div>
			<h1 class="text-center">Album Application</h1><br><br>
			<div class="row centered-form">
		  		<div class="col-xs-12 col-sm-6 col-md-8 col-sm-offset-2 col-md-offset-2">
			  		<div class="login-panel panel panel-default">
				        <div class="panel-heading">
				        	<h1 class="panel-title text-center"><strong>New Album</strong></h1>
				      	</div>
				      	<div class="panel-body text-center">
				    	  	<div class="row">
	                    		<div class="col-xs-6 col-sm-12 col-md-12">
									<%= render 'form' %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

albumapp/app/views/albums/show.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="text-right">
        <%= link_to 'Edit', edit_album_path(@album) %> |
        <%= link_to 'Album Index', albums_path %>
        <br>
      </div>
      <h1 class="text-center">Album Application</h1>
      <br>
      <br>
      <div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Album</strong></h1>
            </div>
            <div class="panel-body text-center">
              <form role="form">
                <p id="notice"><%= notice %></p>
                <p>
                  <strong>Thumbnail:</strong>
                  <%= image_tag @album.thumbnail_url(:small) %>
                </p>
                <p>
                  <strong>Title:</strong>
                  <%= @album.title %>
                </p>
                <p>
                  <strong>Description:</strong>
                  <%= @album.description %>
                </p>
                <div class="row">
                    <div class="text-center">
                        <h5><u><strong>Image Gallery</strong></u></h5>
                    </div>
                    <!-- <div class="row"> -->
                        <!-- <div class="col-md-9"> -->
                            <div class="modal-body">
                              <% @album.images.each do |image| %>
                                <%= link_to [@album, image] do %>
                                  <%= image_tag image.image_url(:thumb) %>
                                <% end %>
                              <% end %>   
                            </div>
                        <!-- </div> -->
                    <!-- </div> -->
                      <div class="col-md-2 col-sm-offset-5">
                        <p><%= link_to 'Upload new photo', new_album_image_path(@album) , class: "btn btn-info btn-block" %></p>
                      </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

albumapp/app/views/home/index.html.erb
<% provide(:title, "Log in") %>
<meta name="viewport" content="width=device-width, initial-scale=1">
<br>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="row">
        <div class="well">
            <h1 class="text-center">Album Application</h1>
            <div class="row centered-form">
                <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <br>
                            <%= link_to 'Sign In', albums_path , class: "list-group-item" , class: "btn btn-info btn-block" %>
                            <br>
                            <%= link_to 'New User? Sign Up', new_user_registration_path , class: "list-group-item" , class: "btn btn-info btn-block" %>
                            <br>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<style>
#container1 {
    background-color: #e2dada;
}

.centered-form {
    margin-top: 50px;
    margin-bottom: 50px;
}

.centered-form .panel {
    background: rgba(255, 255, 255, 0.8);
    box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
}
</style>

albumapp/app/views/images/_form.html.erb
<%= form_for [@album,@image] do |f| %>
  <form class="form-horizontal">
  <% if @image.errors.any? %>
    <div class="form-group" id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <br>
  <div class="panel-body">
    <div class="form-group">
      <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-6 col-md-offset-4">
        <%= f.text_field :name , class: "form-control input-sm" , placeholder: "Name" %><br>
        <%= f.file_field :image , class: "form-control input-sm" , placeholder: "Name" %><br>
        <% if f.object.image? %>
          <%= image_tag f.object.image_url(:small) %>
          <%= f.check_box :remove_image %> 
          <%= f.label :remove_image %>
        <% end %>
        <br>
        <br>
        <div class="actions">
          <%= submit_tag "Create Image", :class => "login-button btn-info" %>
        </div>
      </div>
    </div>
  </div>
  </form>
<% end %>

albumapp/app/views/images/edit.html.erb
<div class="container">
  <div class="row">
    <div class="well">
    	<div class="text-right">
	    	<%= link_to 'Back', album_images_path %>
		</div>
		<h1 class="text-center">Album Application</h1><br>
    	<div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Editing Image</strong></h1>
            </div>
            <div class="panel-body text-center">
				<%= render 'form' %>
			</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>  

albumapp/app/views/images/index.html.erb
<div class="container">
  <div class="row">
    <div class="well">
      <div class="text-right">
        <%= link_to 'New Image', new_album_image_path(@album) %> |
        <%= link_to 'Album', albums_path %>
      </div>
      <h1 class="text-center">Album Application</h1>
      <div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Images</strong></h1>
            </div>
            <div class="panel-body text-center">
              <form role="form">
                <p id="notice"><%= notice %></p>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Images</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @images.each do |image| %>
                      <tr>
                        <td><%= image_tag image.image_url(:thumb) %></td>
                        <td><%= link_to 'Show', album_image_path(@album,image) %></td>
                        <td><%= link_to 'Edit', edit_album_image_path(@album,image) %></td>
                        <td><%= link_to 'Destroy', album_image_path(@album,image), method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

albumapp/app/views/images/new.html.erb
<div class="container">
	<div class="row">
  		<div class="well">
			<div class="text-right">
				<%= link_to 'Back', album_images_path %>
			</div>
			<h1 class="text-center">Album Application</h1><br><br>
			<div class="row centered-form">
		  		<div class="col-xs-12 col-sm-6 col-md-8 col-sm-offset-2 col-md-offset-2">
			  		<div class="login-panel panel panel-default">
				        <div class="panel-heading">
				        	<h1 class="panel-title text-center"><strong>New Image</strong></h1>
				      	</div>
				      	<div class="panel-body text-center">
				    	  	<div class="row">
	                    		<div class="col-xs-6 col-sm-12 col-md-12">
									<%= render 'form' %>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

albumapp/app/views/images/show.html.erb
<div class="container">
  <div class="row">
    <div class="well">
    	<div class="text-right">
  	   	<%= link_to 'Back to Album' , albums_path  %>
				
				<%= link_to 'Back to Images', album_images_path %>
			</div>
			<h1 class="text-center">Album Application</h1><br>
      <div class="row centered-form">
        <!-- <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4"> -->
          <div class="login-panel panel panel-default">
            <div class="panel-heading">
              <h1 class="panel-title text-center"><strong>Gallery</strong></h1>
            </div>
            <div class="panel-body text-center">
              <form role="form">
								<p id="notice"><%= notice %></p>
								<p>
								  <strong>Image:</strong>
								  <%= image_tag @image.image_url(:small) %>
								</p><br>
								<div class="col-xs-12 col-sm-6 col-sm-offset-5 col-md-2">
									<div class="form-group"><%= link_to 'Edit', edit_album_image_path(@album,@image) , class: "btn btn-info btn-block" %></div>
								</div>
							</form>
						</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

albumapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Albumapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>
<%= yield %>
<%= render "layouts/footer" %>
</body>
</html>

albumapp/app/views/user/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :email, :class => 'form-control' %>
    </div>
    <%=f.error_span(:email) %>
  </div>
  <div class="form-group">
    <%= f.label :encrypted_password, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :encrypted_password, :class => 'form-control' %>
    </div>
    <%=f.error_span(:encrypted_password) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_token, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_token, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_token) %>
  </div>
  <div class="form-group">
    <%= f.label :reset_password_sent_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reset_password_sent_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:reset_password_sent_at) %>
  </div>
  <div class="form-group">
    <%= f.label :remember_created_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :remember_created_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:remember_created_at) %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_sign_in_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_sign_in_at) %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_sign_in_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_sign_in_at) %>
  </div>
  <div class="form-group">
    <%= f.label :current_sign_in_ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :current_sign_in_ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:current_sign_in_ip) %>
  </div>
  <div class="form-group">
    <%= f.label :last_sign_in_ip, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :last_sign_in_ip, :class => 'form-control' %>
    </div>
    <%=f.error_span(:last_sign_in_ip) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                albums_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

albumapp/app/views/user/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

albumapp/app/views/user/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:encrypted_password) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_token) %></th>
      <th><%= model_class.human_attribute_name(:reset_password_sent_at) %></th>
      <th><%= model_class.human_attribute_name(:remember_created_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_at) %></th>
      <th><%= model_class.human_attribute_name(:current_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:last_sign_in_ip) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.email %></td>
        <td><%= user.encrypted_password %></td>
        <td><%= user.reset_password_token %></td>
        <td><%= user.reset_password_sent_at %></td>
        <td><%= user.remember_created_at %></td>
        <td><%= user.current_sign_in_at %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.current_sign_in_ip %></td>
        <td><%= user.last_sign_in_ip %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

albumapp/app/views/user/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

albumapp/app/views/user/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @user.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:encrypted_password) %>:</strong></dt>
  <dd><%= @user.encrypted_password %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_token) %>:</strong></dt>
  <dd><%= @user.reset_password_token %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reset_password_sent_at) %>:</strong></dt>
  <dd><%= @user.reset_password_sent_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:remember_created_at) %>:</strong></dt>
  <dd><%= @user.remember_created_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_at) %>:</strong></dt>
  <dd><%= @user.current_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_at) %>:</strong></dt>
  <dd><%= @user.last_sign_in_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.current_sign_in_ip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_sign_in_ip) %>:</strong></dt>
  <dd><%= @user.last_sign_in_ip %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>